---
- name: Configure Ubuntu File Server for One User (Admin Group Access)
  hosts: Server
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Samba
      apt:
        name: samba
        state: present

    - name: Create system user
      user:
        name: "{{ samba_user }}"
        shell: /bin/false
        create_home: yes
        password: "{{ samba_password | password_hash('sha512') }}"
        groups: sudo
        append: yes
        state: present

    - name: Create personal share directory
      file:
        path: "{{ share_path }}"
        state: directory
        owner: "{{ samba_user }}"
        group: sudo
        mode: '0775'

    - name: Add Samba user with password
      expect:
        command: smbpasswd -a {{ samba_user }}
        responses:
          'New SMB password:': "{{ samba_password }}"
          'Retype new SMB password:': "{{ samba_password }}"
      when: samba_user_smb_exists.rc != 0
      register: add_smb_user

    - name: Check if Samba user exists
      command: pdbedit -L -u {{ samba_user }}
      register: samba_user_smb_exists
      failed_when: false

    - name: Configure Samba share for sudo group
      blockinfile:
        path: /etc/samba/smb.conf
        insertafter: '^\[global\]'   # insert after the [global] section
        block: |
          [{{ samba_user }}]
          path = {{ share_path }}
          browsable = yes
          read only = no
          guest ok = no
          admin users = {{ samba_user }}

    - name: Restart Samba service
      systemd:
        name: smbd
        state: restarted
        enabled: yes
